Implement __aws_installed_or_exit

diff --git a/moped-database/hasura-cluster b/moped-database/hasura-cluster
--- a/moped-database/hasura-cluster
+++ b/moped-database/hasura-cluster
@@ -80,6 +80,13 @@ function __is_aws_cli_installed() {
   aws --help 2&>1 /dev/null && echo "TRUE" || echo "FALSE";
 }
 
+function __aws_installed_or_exit() {
+  if [[ $(__is_aws_cli_installed) == "FALSE" ]]; then
+    echo "AWS CLI is not installed, aborting.";
+    exit 1;
+  fi;
+}
+
 #
 # Check snapshots folder
 #
